# 使用时请更新LUNAN_AUTH_ENDPOINT MYSQL_ROOT_PASSWORD
# 并配置conf/app.conf
version: '3.1'
services:
  casdoor:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      LUNAN_AUTH_ENDPOINT: ""
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/conf/
  db:
    restart: always
    image: mysql:8.0.25
    platform: linux/amd64
    ports:
      - "13307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /usr/local/docker/mysql:/var/lib/mysql